### ISSUE TITLE
Option to Force World Type and not allow people to change.

### ISSUE THREAD

**Issue by furtabs** [ezterry/DefaultWorldGenerator-port#15]
Okay so curently. If i set the world type to any type without Void Island Control Or YUNoMakeGoodMap installed it is fine. If one of those mods is installed it locks it to that type. As an example in your mod if i disable force locking and set default type to a standard default type it still overrides. This is the same when you actually lock the type in the mod since it still overides to a Void World.

**Comment by ezterry** [comment]
I'm not sure what you are asking,
If you lock the world type I lock the field in the new game screens (not the mod configuration screen)

However if the mod is coded to pre-set the world type that can take precedence regardless of what my mod is trying to do.

Also some mods override the default world generator buggy ways.. I've seen at least one historically that if you make a void world, then exit to menu and make a default world.. the void world loader will still be installed due to how the override worked inside the mod. 

If it helps I lock down the world here to a custom generator + preset and import custom loot tables into the "datapack" on world load
https://www.curseforge.com/minecraft/modpacks/wasteland-topia
