### ISSUE TITLE
Add options to disable world config buttons

### ISSUE THREAD

**Issue by Dragnier** [ezterry/DefaultWorldGenerator-port#7]
I would like to request the ability to disable the more world options button and the choice of survival/creative/hardcore.

In addition, I would like to add an option to force adventure mode on world loading without enabling cheats if that is possible.

**Comment by ezterry** [comment]
I'd need a very convincing use case to disable the more world options button.  (making it slightly harder to enable/disable cheats or see the pre-set world settings in single player is not in my opinion acceptable)

As for the adventure mode, (or creative/survival for that mater) you could use the commands/data parts of the mod to load a script that forces a players mode.  Even to simulate hardcore (ie force them into spectator after they die) .. in fact this can be done in a way that even with cheats enabled it would not be possible to force yourself into another mode (without deleting the mcfunction anyway) since every tick it would correct any player in the wrong game mode

**Comment by Dragnier** [comment]
You are correct that disabling cheats is the main reason for the suggestion. I don't understand why that isn't sufficient reason. Some people cannot help but cheat in spite of themselves; whether due to a lack of self-control or simple impatience. My son has relatively severe ADHD and is among those people. I was simply looking for a way to remove the temptation for him if possible.

Thinking about it, the option to disable the cheats button, force survival, and disable the Open to Multiplayer button of the in-game menu would work instead of denying the entire More World Options. The ability to pre-define a suggested seed plus those features would make your mod perfect for my needs. I understand if you don't want to go that route though.
